apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.elkrey.service: mongo-claim0
  name: mongo-claim0
  namespace: chat-socket-challenge-angular-chat-net
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
